apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
  server:
    route:
      enabled: true   # optional if you want ingress/route
    service:
      type: NodePort  # ✅ valid in v1beta1 for most ArgoCD Operator versions
